spring.application.name=FarmaBot_SOS

server.port = 8081

qdrant.url=http://localhost:6333
qdrant.collection=drogueria_catalogo

llm.api.url=
llm.api.key=

llm.embedding.model=text-embedding-3-small

llm.chat.model=gpt-4o-mini

alert.webhook.url=https://tu-webhook-o-bot-telegram.com/sos