spring.application.name=FarmaBot_SOS

server.port = 8081

qdrant.url=http://localhost:6333
qdrant.collection=drogueria_catalogo

llm.api.url=https://openrouter.ai/api/v1
llm.api.key=

llm.embedding.model=google/gemini-embedding-2

llm.chat.model=gpt-4o-mini

alert.webhook.url=https://reselect-contort-carwash.ngrok-free.dev/webhook/esEmergencia

spring.datasource.url=jdbc:mysql://localhost:3306/drogueria?useSSL=false&serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect