spring.application.name=FarmaBot_SOS

server.port = 8081

qdrant.url=http://localhost:6333
qdrant.collection=drogueria_catalogo

llm.api.url=https://api.tu-proveedor-llm.com/v1
llm.api.key=${LLM_API_KEY}

llm.embedding.model=text-embedding-3-small

llm.chat.model=gpt-4o-mini

alert.webhook.url=https://tu-webhook-o-bot-telegram.com/sos